# Generated by Django 4.2.15 on 2025-03-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
