# Generated by Django 4.2.18 on 2025-02-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="cartitems",
            old_name="cart_id",
            new_name="cart",
        ),
        migrations.RenameField(
            model_name="cartitems",
            old_name="dish_id",
            new_name="dish",
        ),
    ]
