# Generated by Django 4.2.18 on 2025-02-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
    ]
